language: python
sudo: required

cache:
  directories:
    - $HOME/miniconda3

before_install:
  - . ./scripts/install_miniconda.sh
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=":99.0"

install:
  - . ./scripts/create_testenv.sh
  - pip install coveralls
  - conda list && pip freeze

script:
  - if [ -z ${TEST_STYLE} ] && make check
  - make test

env:
  - PYTHON_VERSION=3.0
  - PYTHON_VERSION=3.1
  - PYTHON_VERSION=3.2
  - PYTHON_VERSION=3.3
  - PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.6 TEST_STYLE="True"
  - PYTHON_VERSION=3.7 TEST_STYLE="True"

after_success:
  - coveralls
