language: python

sudo: required

cache:
  directories:
  - "$HOME/miniconda3"

before_install:
- ". ./scripts/install_miniconda.sh"

install:
- ". ./scripts/create_testenv.sh"
- pip install coveralls
- conda list && pip freeze

env:
  matrix:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6 TEST_STYLE="True"
  - PYTHON_VERSION=3.7 TEST_STYLE="True"
  - PYTHON_VERSION=3.7 TEST_DOCS="True"

script: "./scripts/run_tests.sh"

stages:
- test
- deploy

jobs:
  include:
  - stage: deploy
    name: deploy
    if: branch = master AND type = push
    env: PYTHON_VERSION=3.7 TEST_DOCS="True"
    local_dir: docs/html
    script: skip
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep_history: true
      on:
        branch: master


after_success:
- coveralls
