language: python
sudo: required

cache:
  directories:
    - $HOME/miniconda3

before_install:
  - . ./scripts/install_miniconda.sh
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=":99.0"

install:
  - . ./scripts/create_testenv.sh
  - pip install coveralls
  - conda list && pip freeze

script:
  - black --check compress_pickle;
  - pylint compress_pickle;
  - pytest -v compress_pickle/tests/ --cov=compress_pickle/ --html=testing-report.html --self-contained-html;

env:
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

after_success:
  - coveralls
