language: python


python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'


install:
    pip install --upgrade pip;
    pip install -r requirements-dev.txt;
    pip install -e .;


script:
    black --check compress_pickle;
    pylint compress_pickle;
    pytest -v compress_pickle/tests/ --cov=compress_pickle/ --html=testing-report.html --self-contained-html;
